# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('slug', 'room')]),
        ),
    ]
