# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20161108_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([]),
        ),
    ]
