# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.House'),
            preserve_default=False,
        ),
    ]
