# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20161229_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31),
        ),
    ]
