# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('item', '0011_auto_20161229_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'permissions': (('view_house', 'Can view house'),)},
        ),
        migrations.AddField(
            model_name='houseuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.House'),
        ),
        migrations.AddField(
            model_name='houseuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='houseuserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='houseuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
    ]
