# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_add_house_object_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31),
        ),
    ]
