# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_remove_room_slug_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'permissions': (('view_house', 'Can view house'), ('is_resident', 'Can edit and delete rooms,places and items in the house'))},
        ),
    ]
