from django.conf.urls import url

from .views import (
  ItemList, ItemDetail, ItemCreate, ItemUpdate, ItemDelete,
  PlaceList, PlaceDetail, PlaceCreate, PlaceUpdate, PlaceDelete,
  RoomList, RoomDetail, RoomCreate, RoomUpdate, RoomDelete,
  search)

urlpatterns = [
  url(r'^item/$',
    ItemList.as_view(),
    name='item_list'),
  url(r'^item/create/$',
    ItemCreate.as_view(),
    name='item_create'),
  url(r'^item/update/(?P<slug>[\w\-]+)/$',
    ItemUpdate.as_view(),
    name='item_update'),
  url(r'^item/delete/(?P<slug>[\w\-]+)/$',
    ItemDelete.as_view(),
    name='item_delete'),
  url(r'^item/(?P<slug>[\w\-]+)/$',
    ItemDetail.as_view(),
    name='item_detail'),
  url(r'^place/$',
    PlaceList.as_view(),
    name='place_list'),
  url(r'^place/create/$',
    PlaceCreate.as_view(),
    name='place_create'),
  url(r'^place/update/(?P<slug>[\w\-]+)/$',
    PlaceUpdate.as_view(),
    name='place_update'),
  url(r'^place/delete/(?P<slug>[\w\-]+)/$',
    PlaceDelete.as_view(),
    name='place_delete'),
  url(r'^place/(?P<slug>[\w\-]+)/$',
    PlaceDetail.as_view(),
    name='place_detail'),
  url(r'^room/$',
    RoomList.as_view(),
    name='room_list'),
  url(r'^room/create/$',
    RoomCreate.as_view(),
    name='room_create'),
  url(r'^room/update/(?P<slug>[\w\-]+)/$',
    RoomUpdate.as_view(),
    name='room_update'),
  url(r'^room/delete/(?P<slug>[\w\-]+)/$',
    RoomDelete.as_view(),
    name='room_delete'),
  url(r'^room/(?P<slug>[\w\-]+)/$',
    RoomDetail.as_view(),
    name='room_detail'),
  url(r'^search/$',
    search,
    name='item_search'),
]
